name: Build Debug APK

on:
  pull_request:
    branches:
      - main
      - release/*

concurrency:
  group: build-debug-apk-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 3. Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      # 4. Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      # Create local.properties (if needed for your SDK configuration)
      - name: Create local.properties file
        run: echo "${{ secrets.LOCAL_PROPERTIES_DEBUG }}" > local.properties

      - name: Decode JKS keystore
        run: echo "${{ secrets.KEYSTORE_BASE64_DEBUG }}" | base64 --decode > app/keystore-debug.jks

      # 5. Make the Gradle wrapper executable
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 6. Build the Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug
        env:
          KEYSTORE_PASSWORD_DEBUG: ${{ secrets.KEYSTORE_PASSWORD_DEBUG }}
          KEY_ALIAS_DEBUG: ${{ secrets.KEY_ALIAS_DEBUG }}
          KEY_PASSWORD_DEBUG: ${{ secrets.KEY_PASSWORD_DEBUG }}

      # 7. Create a Debug Release (pre-release)
      - name: Create Debug Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          # Use the PR number if available; otherwise, fallback to the run number
          tag_name: debug-pr-${{ github.event.pull_request.number || github.run_number }}
          name: Debug APK for ${{ github.event.pull_request.title }}
          prerelease: true
          overwrite: true
          files: app/build/outputs/apk/debug/app-debug.apk

      # 9. Comment on the PR with a link to download the debug APK
      - name: Comment on PR with debug APK link
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            A debug APK build for this PR is available for download [here](${{ steps.create_release.outputs.url }}).