name: Build and Release Android App

concurrency:
  group: build-and-release-android-app
  cancel-in-progress: true

on:
  push:
    branches:
      - main

permissions:
  contents: write

env: # avoid repeating these in every job
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
  JKS_B64: ${{ secrets.KEYSTORE_BASE64 }}

jobs:
  build-aab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create local.properties
        run: echo "$LOCAL_PROPERTIES" > local.properties

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Decode keystore
        run: echo "$JKS_B64" | base64 --decode > app/keystore.jks

      - name: Increment Version Numbers
        id: increment_version
        run: bash increment_version.sh

      - name: Build bundleRelease
        run: ./gradlew --no-daemon --configuration-cache bundleRelease

      - name: Upload AAB + symbols
        uses: actions/upload-artifact@v4
        with:
          name: aab
          path: |
            app/release/app-release.aab
            app/release/native-debug-symbols.zip

  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create local.properties
        run: echo "$LOCAL_PROPERTIES" > local.properties

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Increment Version Numbers
        id: increment_version
        run: bash increment_version.sh

      - name: Decode keystore
        run: echo "$JKS_B64" | base64 --decode > app/keystore.jks

      - name: Build assembleRelease
        run: ./gradlew --no-daemon --configuration-cache assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/release/app-release.apk

  release:
    needs: [ build-aab, build-apk ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download AAB artifact
        uses: actions/download-artifact@v4
        with:
          name: aab

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: apk

      - name: Increment Version Numbers
        id: increment_version
        run: bash increment_version.sh

      - name: Create GitHub Release and upload the bundle
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.increment_version.outputs.new_version }}
          files: |
            **/app-release.aab
            **/native-debug-symbols.zip
            app-release.apk

      - name: Commit Version Number Increment and Push
        run: |
          git config --local user.email "github-actions"
          git config --local user.name "github-actions@github.com"
          git add gradle.properties
          git commit -m "[skip ci] Increment version number"
          git push